spring.application.name=task-service
server.port=8081

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# PHASE 1 FIX: Route UserServiceClient through AWS ALB
user.service.url=http://microservices-alb-483529590.us-east-1.elb.amazonaws.com:8080